version: "3.8"

services:
  # MongoDB service
  mongo_db:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db

    # Node API service
  backend:
    build:
      context: ../backend
    ports:
      - 8081:8080
    volumes:
      - /data/backend_data:/myapp/data
    environment:
      DB_URL: mongodb+srv://${DB_USER}:${PASSWORD}@cluster0.h1hajx0.mongodb.net/?retryWrites=true&w=majority
      DB_NAME: mydatabase
    env_file: ../backend/.env
    depends_on:
      - mongo_db

  # react app
  frontend:
    build: .
    ports:
      - 3001:3000

volumes:
  mongo_db: {}
