version: "3.8"

services:
  # MongoDB service
  mongo_db:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db
    networks:
      - my-network

  # Node API service
  server:
    build:
      context: ../server
    ports:
      - 8081:8080
    volumes:
      - /data/server_data:/myapp/data
    environment:
      DB_URL: mongodb://mongo_db:27017/mydatabase
    env_file: ../server/.env
    depends_on:
      - mongo_db
    networks:
      - my-network

  # react app
  client:
    build: .
    ports:
      - 3001:3000
    networks:
      - my-network

volumes:
  mongo_db: {}

networks:
  my-network:
