version: "3"
services:

  server:
    container_name: server
    build: 
      context: ../M5-Backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 4000:4000
    depends_on:
      - mongo
    networks:
      - networkThree

  client:
    container_name: client
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - server
    networks:
      - networkThree

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    networks:
      - networkThree

networks:
  networkThree:

# volumes:
