version: "3"
services:
  server:
    build: ../M5-Backend
    restart: always
    ports:
      - 4000:4000
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://127.0.0.1:27017/bookstore
  client:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - server
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=bookstore
