version: "3.8"

services:
  frontend:
    build: .
    ports:
      - 3001:3000
  # backend:
  #   build: .
  #   ports:
  #     - 3002:3002
  #   environment:
  #     DB_URL: mongodb://db/m5
  # db:
  #   image: mongo:4.0-xenial
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - m5:/data/db

volumes:
  m5:
